version: '3.8'

services:
  # Servicio de laboratorio
  laboratorio-service:
    build: .
    container_name: laboratorio-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=laboratorio_db
      - DB_USER=laboratorio_user
      - DB_PASSWORD=laboratorio_password
      - FRONTEND_URL=http://localhost:3000
      - BASE_URL=http://localhost:3003
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
    networks:
      - laboratorio-network
    restart: unless-stopped

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: laboratorio-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laboratorio_db
      - MYSQL_USER=laboratorio_user
      - MYSQL_PASSWORD=laboratorio_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql:ro
    networks:
      - laboratorio-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (Interfaz web para MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laboratorio-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=laboratorio_user
      - PMA_PASSWORD=laboratorio_password
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - laboratorio-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  laboratorio-network:
    driver: bridge